### PR TITLE
 Updated to Featherlight 1.7.14 with patch for WebP support (featherlight#412)

### PR DESCRIPTION
**Pull request by waseigo**

### CODE REVIEW

**Comment by w00fz** [comment]
@waseigo i take you tested this? :) Is it fully backward compatible that you know of?

**Comment by waseigo** [comment]
I tested it with Grav 1.5 and 1.6, and am now using it on websites running
1.7.x.

**Comment by Rotzbua** [comment]
@waseigo Can you add the new image format AVIF? Would avoid future problems ;-)

**Review by Rotzbua — APPROVED** [review]

**Comment by rhukster** [comment]
Thanks!

**Pull request merged**
