### PR TITLE
v1.4.0 - AMD module support and closeOnEsc fix

### PR DESCRIPTION
**Pull request by khanduras**
Allows output for AMD module for RequireJS

### CODE REVIEW

**Comment by flaviocopes** [comment]
Version 1.4.0 has not been released yet, so you can drop the 1.4.1 version and simply add the changelog to 1.4.0

**Comment by flaviocopes** [comment]
Good improvement btw 👍

**Comment by khanduras** [comment]
Updated. I'll be looking at other official plugins and creating output for AMD modules as I need them. :)

**Comment by flaviocopes** [comment]
👍

**Pull request merged**
