### PR TITLE
Put init JS into separate file

### PR DESCRIPTION
**Pull request by kitzberger**
This allows to override the default init script, e.g. to add an image caption to the lightbox.

### CODE REVIEW

**Comment by kitzberger** [comment]
Any progress and/or feedback on this one? ;-)

**Comment by flaviocopes** [comment]
Slipped under the radar - looking now.

**Comment by flaviocopes** [comment]
Looking good!

**Comment by kitzberger** [comment]
Great, thanks a lot ;-)

**Pull request merged**
